### ISSUE TITLE
Alternative schematic & question about use of SS, A1,2,3,5

### ISSUE THREAD

**Issue by gwideman** [felias-fogg/dw-link#13]
I spent some time studying the dw-link shield and your extensive and thoughtful discussion of it.  I ended up rearranging the schematic somewhat and added some annotations to make it make it easier for me to follow. I include an image of that below, in case others might also be interested.

This led me to a couple of puzzles, explanations of which could benefit your documentation pages.

1. I see that you implemented ISP using the host Arduino's MISO and MOSI pins, but using SS (D10) instead of SCK (D13) for the SPI clock function. It seems the firmware doesn't use the built-in SPI hardware, instead bit-banging those pins.  This is somewhat at odds with the breadboard version discussed on page quickstart.md, and I didn't see a discussion of this anomaly, which would be interesting.

2.  I also see that you connect pins A1,2,3,5 to the ISP and debugWire (Reset) wires.  I didn't find a reference to these bits in the firmware. Are these connections to allow some testing of the shield, or some other purpose? Again, different from the quickstart.md discussion, and would add interestingly to your implementation discussion.

![image](https://github.com/felias-fogg/dw-link/assets/1243021/d1c3ea60-20f6-498c-835d-c5023242f1e1)

**Comment by felias-fogg** [comment]
Hi,

looks very good! Did you use KiCAD? And could you send me the source?

And yes, the analog inputs are used for testing the board's functions. There is a sketch for that in the repo "testprobe"

I switched from SCLK to SS because SCLK cannot be used as an open drain output. SCK drives the builtin LED on the UNO board. Using bit-banging is actually not as bad as one may think. With 19200 baud, which is the standard speed for the Arduino ISP programmer, bit-banging is fast enough. 

Cheers,
Bernhard

**Comment by gwideman** [comment]
> And yes, the analog inputs are used for testing the board's functions. There is a sketch for that in the repo "testprobe"

Ah, thanks, that explains that feature.

> I switched from SCLK to SS because SCLK cannot be used as an open drain output. SCK drives the
>  builtin LED on the UNO board.

OK, that explains why the special treatment of D13.

But I guess now I'm not clear on why open drain is needed for MOSI and "SCK" (SS).  I thought that SPI Master wires are unidirectional from the Master, no?   Perhaps you know of a scenario where the target system hardware is wired for ISP/SPI-slave role, but at some point sends data out on its MOSI or SCK wires?  

Or is this just a way to implement level shifting with jumper selectable VCC, and is otherwise unidirectional?

**Comment by felias-fogg** [comment]
Thanks! It is now part of the manual ;-).
